services:

  # ==========================
  # ZOOKEEPER + KAFKA
  # ==========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: notifications_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: notifications_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  # ==========================
  # USER SERVICE
  # ==========================
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - PORT=3000
      - DATABASE_URL=${USER_DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRES=${ACCESS_EXPIRES}
      - REFRESH_EXPIRES=${REFRESH_EXPIRES}
    networks:
      - app-network

  # ==========================
  # POST MIGRATION
  # ==========================
  post-migrate:
    build: ./post-service
    container_name: post-migrate
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DATABASE_URL=${POST_DATABASE_URL}
    command: sh -c "npm run migrate up"
    networks:
      - app-network
    restart: "no"

  # ==========================
  # POST SERVICES
  # ==========================
  post-service-1:
    build: ./post-service
    container_name: post-service-1
    depends_on:
      post-migrate:
        condition: service_completed_successfully
    environment:
      - PORT=3002
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${POST_DATABASE_URL}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    networks:
      - app-network

  post-service-2:
    build: ./post-service
    container_name: post-service-2
    depends_on:
      post-migrate:
        condition: service_completed_successfully
    environment:
      - PORT=3002
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${POST_DATABASE_URL}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    networks:
      - app-network

  # ==========================
  # COMMUNITY SERVICE
  # ==========================
  community-service:
    build: ./community-service
    container_name: community-service
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=3003
      - DATABASE_URL=${COMMUNITY_DATABASE_URL}
      - PG_HOST=${COMMUNITY_PG_HOST}
      - PG_PORT=${COMMUNITY_PG_PORT}
      - PG_USER=${COMMUNITY_PG_USER}
      - PG_PASSWORD=${COMMUNITY_PG_PASSWORD}
      - PG_DATABASE=${COMMUNITY_PG_DATABASE}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - app-network

  # ==========================
  # NOTIFICATION SERVICE
  # ==========================
  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=3004
      - DATABASE_URL=${NOTIFICATION_DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - CORS_ORIGINS=${CORS_ALLOWED_ORIGIN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
