services:

  # ==========================
  # ZOOKEEPER + KAFKA
  # ==========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: notifications_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: notifications_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - app-network

  # ==========================
  # USER SERVICE
  # ==========================
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network

  # ==========================
  # POST MIGRATION
  # ==========================
  post-migrate:
    build: ./post-service
    container_name: post-migrate
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - DATABASE_URL=${POST_DATABASE_URL}
    command: sh -c "npm run migrate up"
    networks:
      - app-network
    restart: "no"

  # ==========================
  # POST SERVICES
  # ==========================
  post-service-1:
    build: ./post-service
    container_name: post-service-1
    ports:
      - "3002:3002"
    depends_on:
      post-migrate:
        condition: service_completed_successfully
    environment:
      - PORT=3002
    networks:
      - app-network

  post-service-2:
    build: ./post-service
    container_name: post-service-2
    # không expose ra host, vì chỉ cần 1 node cho NGINX
    depends_on:
      post-migrate:
        condition: service_completed_successfully
    environment:
      - PORT=3002
    networks:
      - app-network

  # ==========================
  # COMMUNITY SERVICE
  # ==========================
  community-service:
    build: ./community-service
    container_name: community-service
    ports:
      - "3003:3003"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=3003
    networks:
      - app-network

  # ==========================
  # NOTIFICATION SERVICE
  # ==========================
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=3004
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
